function [out] = conv(ifmap ,y ,x ,depth)
    if (x == 1) && (y == 1)
        out = nearest(sum(ifmap(y   ,x   ,1:depth)/4)...
                    +sum( ifmap(y   ,x+1 ,1:depth)/8)...
                    +sum( ifmap(y+1 ,x   ,1:depth)/8)...
                    +sum( ifmap(y+1 ,x+1 ,1:depth)/16));
    elseif (x == 8) && (y == 1)
        out = nearest(sum(ifmap(y  ,x-1 ,1:depth)/8)...
                    +sum(ifmap(y   ,x   ,1:depth)/4)...
                    +sum(ifmap(y+1 ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y+1 ,x   ,1:depth)/8));
    elseif (x == 1) && (y == 8)
        out = nearest(sum(ifmap(y-1 ,x   ,1:depth)/8)...
                    +sum(ifmap(y-1  ,x+1 ,1:depth)/16)...
                    +sum(ifmap(y    ,x   ,1:depth)/4)...
                    +sum(ifmap(y    ,x+1 ,1:depth)/8));
    elseif (x == 8) && (y == 8)
        out = nearest(sum(ifmap(y-1 ,x-1 ,1:depth)/8)...
                    +sum(ifmap(y-1  ,x   ,1:depth)/16)...
                    +sum(ifmap(y    ,x-1 ,1:depth)/4)...
                    +sum(ifmap(y    ,x   ,1:depth)/8));
    elseif (x == 1)
        out = nearest(sum(ifmap(y-1 ,x   ,1:depth)/8)...
                    +sum(ifmap(y-1  ,x+1 ,1:depth)/16)...
                    +sum(ifmap(y    ,x   ,1:depth)/4)...
                    +sum(ifmap(y    ,x+1 ,1:depth)/8)...
                    +sum(ifmap(y+1  ,x   ,1:depth)/8)...
                    +sum(ifmap(y+1  ,x+1 ,1:depth)/16));
    elseif (x == 8)
        out = nearest(sum(ifmap(y-1 ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y-1  ,x   ,1:depth)/8)...
                    +sum(ifmap(y    ,x-1 ,1:depth)/8)...
                    +sum(ifmap(y    ,x   ,1:depth)/4)...
                    +sum(ifmap(y+1  ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y+1  ,x   ,1:depth)/8));
    elseif (y == 1)
        out = nearest(sum(ifmap(y  ,x-1 ,1:depth)/8)...
                    +sum(ifmap(y   ,x   ,1:depth)/4)...
                    +sum(ifmap(y   ,x+1 ,1:depth)/8)...
                    +sum(ifmap(y+1 ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y+1 ,x   ,1:depth)/8)...
                    +sum(ifmap(y+1 ,x+1 ,1:depth)/16));
    elseif (y == 8)
        out = nearest(sum(ifmap(y-1 ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y-1  ,x   ,1:depth)/8)...
                    +sum(ifmap(y-1  ,x+1 ,1:depth)/16)...
                    +sum(ifmap(y    ,x-1 ,1:depth)/8)...
                    +sum(ifmap(y    ,x   ,1:depth)/4)...
                    +sum(ifmap(y    ,x+1 ,1:depth)/8));
    else
        out = nearest(sum(ifmap(y-1 ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y-1  ,x   ,1:depth)/8)...
                    +sum(ifmap(y-1  ,x+1 ,1:depth)/16)...
                    +sum(ifmap(y    ,x-1 ,1:depth)/8)...
                    +sum(ifmap(y    ,x   ,1:depth)/4)...
                    +sum(ifmap(y    ,x+1 ,1:depth)/8)...
                    +sum(ifmap(y+1  ,x-1 ,1:depth)/16)...
                    +sum(ifmap(y+1  ,x   ,1:depth)/8)...
                    +sum(ifmap(y+1  ,x+1 ,1:depth)/16));
    end
end








