function [out] = median(ifmap ,y ,x ,z)
    if (x == 1) && (y == 1)
        out = 0;
    elseif (x == 8) && (y == 1)
        out = 0;
    elseif (x == 1) && (y == 8)
        out = 0;
    elseif (x == 8) && (y == 8)
        out = 0;
    elseif (x == 1)
        sorting = sort([0,0,0 ...
                   ,ifmap(y-1  ,x   ,z)...
                   ,ifmap(y-1  ,x+1 ,z)...
                   ,ifmap(y    ,x   ,z)...
                   ,ifmap(y    ,x+1 ,z)...
                   ,ifmap(y+1  ,x   ,z)...
                   ,ifmap(y+1  ,x+1 ,z)]);
        out = sorting(5);
    elseif (x == 8)
        sorting = sort([0,0,0 ...
                   ,ifmap(y-1 ,x-1 ,z)...
                   ,ifmap(y-1  ,x   ,z)...
                   ,ifmap(y    ,x-1 ,z)...
                   ,ifmap(y    ,x   ,z)...
                   ,ifmap(y+1  ,x-1 ,z)...
                   ,ifmap(y+1  ,x   ,z)]);
        out = sorting(5);
    elseif (y == 1)
        sorting = sort([0,0,0 ...
                   ,ifmap(y  ,x-1 ,z)...
                   ,ifmap(y   ,x   ,z)...
                   ,ifmap(y   ,x+1 ,z)...
                   ,ifmap(y+1 ,x-1 ,z)...
                   ,ifmap(y+1 ,x   ,z)...
                   ,ifmap(y+1 ,x+1 ,z)]);
        out = sorting(5);
    elseif (y == 8)
        sorting = sort([0,0,0 ...
                   ,ifmap(y-1 ,x-1 ,z)...
                   ,ifmap(y-1  ,x   ,z)...
                   ,ifmap(y-1  ,x+1 ,z)...
                   ,ifmap(y    ,x-1 ,z)...
                   ,ifmap(y    ,x   ,z)...
                   ,ifmap(y    ,x+1 ,z)]);
        out = sorting(5);
    else
        sorting = sort([ifmap(y-1 ,x-1 ,z)...
                   ,ifmap(y-1  ,x   ,z)...
                   ,ifmap(y-1  ,x+1 ,z)...
                   ,ifmap(y    ,x-1 ,z)...
                   ,ifmap(y    ,x   ,z)...
                   ,ifmap(y    ,x+1 ,z)...
                   ,ifmap(y+1  ,x-1 ,z)...
                   ,ifmap(y+1  ,x   ,z)...
                   ,ifmap(y+1  ,x+1 ,z)]);
        out = sorting(5);
    end
end








