function [out] = sobel_y(ifmap ,y ,x ,z)
    if (x == 1) && (y == 1)
        out =  (ifmap(y   ,x   ,z)*0)...
              +(ifmap(y   ,x+1 ,z)*0)...
              +(ifmap(y+1 ,x   ,z)*2)...
              +(ifmap(y+1 ,x+1 ,z)*1);
    elseif (x == 8) && (y == 1)
        out =  (ifmap(y   ,x-1 ,z)*0)...
              +(ifmap(y   ,x   ,z)*0)...
              +(ifmap(y+1 ,x-1 ,z)*1)...
              +(ifmap(y+1 ,x   ,z)*2);
    elseif (x == 1) && (y == 8)
        out =  (ifmap(y-1  ,x   ,z)*(-2))...
              +(ifmap(y-1  ,x+1 ,z)*(-1))...
              +(ifmap(y    ,x   ,z)*0)...
              +(ifmap(y    ,x+1 ,z)*0);
    elseif (x == 8) && (y == 8)
        out =  (ifmap(y-1  ,x-1 ,z)*(-1))...
              +(ifmap(y-1  ,x   ,z)*(-2))...
              +(ifmap(y    ,x-1 ,z)*0)...
              +(ifmap(y    ,x   ,z)*0);
    elseif (x == 1)
        out =  (ifmap(y-1  ,x   ,z)*(-2))...
              +(ifmap(y-1  ,x+1 ,z)*(-1))...
              +(ifmap(y    ,x   ,z)*0)...
              +(ifmap(y    ,x+1 ,z)*0)...
              +(ifmap(y+1  ,x   ,z)*2)...
              +(ifmap(y+1  ,x+1 ,z)*1);
    elseif (x == 8)
        out =  (ifmap(y-1  ,x-1 ,z)*(-1))...
              +(ifmap(y-1  ,x   ,z)*(-2))...
              +(ifmap(y    ,x-1 ,z)*0)...
              +(ifmap(y    ,x   ,z)*0)...
              +(ifmap(y+1  ,x-1 ,z)*1)...
              +(ifmap(y+1  ,x   ,z)*2);
    elseif (y == 1)
        out =  (ifmap(y   ,x-1 ,z)*0)...
              +(ifmap(y   ,x   ,z)*0)...
              +(ifmap(y   ,x+1 ,z)*0)...
              +(ifmap(y+1 ,x-1 ,z)*1)...
              +(ifmap(y+1 ,x   ,z)*2)...
              +(ifmap(y+1 ,x+1 ,z)*1);
    elseif (y == 8)
        out =  (ifmap(y-1  ,x-1 ,z)*(-1))...
              +(ifmap(y-1  ,x   ,z)*(-2))...
              +(ifmap(y-1  ,x+1 ,z)*(-1))...
              +(ifmap(y    ,x-1 ,z)*0)...
              +(ifmap(y    ,x   ,z)*0)...
              +(ifmap(y    ,x+1 ,z)*0);
    else
        out =  (ifmap(y-1  ,x-1 ,z)*(-1))...
              +(ifmap(y-1  ,x   ,z)*(-2))...
              +(ifmap(y-1  ,x+1 ,z)*(-1))...
              +(ifmap(y    ,x-1 ,z)*0)...
              +(ifmap(y    ,x   ,z)*0)...
              +(ifmap(y    ,x+1 ,z)*0)...
              +(ifmap(y+1  ,x-1 ,z)*1)...
              +(ifmap(y+1  ,x   ,z)*2)...
              +(ifmap(y+1  ,x+1 ,z)*1);
    end
end